#' @title in convex hull
#'
#' @description  To test if a given point is inside the convex hull. \code{TRUE}  if the point  lies within the hull and \code{FALSE} if it
#' lies outwith the hull 
#' 
#' @param  points points to make convex hull
#' @param test_points: dataframe or matrix  \code{n}-by-\code{dim} of points to check. 
#' @return A \code{n*m} vector containing the result. True if a given point was inside the convexhull , otherwise false
#' @examples 
#' # Define points to create the convex hull
#' x <- c(30, 70, 20, 50, 40, 70)
#' y <- c(35, 80, 70, 50, 60, 20)
#' p <- data.frame(x, y)
#' ch <- convex_hull(points = p)
#' # Check if some new points are in the convex hull
#' new = data.frame(c(20, 50), c(20, 50))
#' checks <- in_convex_hull(hull=ch, test_points = new)
#' 
#' @export in_convex_hull
  in_convex_hull <- function(hull=NULL, test_points=NULL) {
  
    # Check directory writable
  	tmpdir <- tempdir()
  	# R should guarantee the tmpdir is writable, but check in any case
  	if (file.access(tmpdir, 2) == -1) {
  		stop(paste("Unable to write to R temporary directory", tmpdir, "\n"))
  	}
  	
  	# Coerce the input to be matrix
  	if(is.null(test_points)){
  		stop(paste("test_points must be an n-by-d dataframe or matrix", "\n"))
  	}
  	if(!is.data.frame(test_points) & !is.matrix(test_points)){
  	  stop(paste("test_points must be a dataframe or matrix", "\n"))
  	}
  	if (is.data.frame(test_points)) {
  	  test_points <- as.matrix(test_points)
  	}
  	# Make sure we have real-valued input
  	storage.mode(test_points) <- "double"
  	# We need to check for NAs in the input, as these will crash the C code.
  	if (any(is.na(test_points))) {
  		stop("test_points should not contain any NAs")
  	}
  	
  	# Check convex hull
  	if(is.null(hull)){
  		stop(paste("hull must be convex hull generated by convex_hull", "\n"))
  	}  	
	  # Extract the convex hull points from the convex hull object
    points <- hull$hull_points
    # Make sure we have real-valued input
    storage.mode(points) <- "double"
    
    # Check that the test points have the same dimensions as the convex hull
    # TO DO!
    
    # Specify the Qhull options: http://www.qhull.org/html/qh-optq.htm
    options <- "Qt"
    
    # Call C function to create the convex hull
    convex <- .Call("C_convex", points, options, tmpdir, PACKAGE="alphashape")
    
    # Call C function to check if points are inside the convex hull
    return(.Call("C_inconvexhull", convex$convex_hull, test_points, PACKAGE="alphashape"))
    
  }